apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscode-server
  template:
    metadata:
      labels:
        app: vscode-server
    spec:
      containers:
      - name: vscode-server
        image: your_dockerhub_username/vscode-server
        ports:
        - containerPort: 8080
        env:
        - name: PASSWORD
          value: "your_password"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
