apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-vscode-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-vscode-server
  template:
    metadata:
      labels:
        app: app-vscode-server
    spec:
      containers:
      - name: app-vscode-server
        image: aongtosan/app-vscode-server