apiVersion: v1
kind: Service
metadata:
  name:  app-code-server-service
  labels: 
    app : app-code-server-service
spec:
  type: NodePort
  selector: 
    app: app-vscode-server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002