apiVersion: v1
kind: Service
metadata:
  name:  app-game-test-service
  labels: 
    app : app-game-test-service
spec:
  type: NodePort
  selector: 
    app: app-game-test
  ports:
    - port: 9999
      targetPort: 5555
      nodePort: 30001
      protocol: TCP
      name : app-game-test-service
